### ISSUE TITLE
Cannot use ipv6

### ISSUE THREAD

**Issue by mberlinger3** [hotio/rflood#5]
With the most recent version, ipv6 seems to not be working due to the ip6-restore command not being found.

Possibly similar to the issue with alpine dockers:
* https://github.com/linuxserver/docker-wireguard/issues/208

**Comment by mrhotio** [comment]
Are you certain, because iirc last time I fixed this, the command was found…

**Comment by mrhotio** [comment]
Ok, should have first looked at the issue, probably the same problem, will have a look in a few hours

**Comment by mberlinger3** [comment]
Thanks for explicitly adding it. It doesnt seem to have fixed the issue tho. ip6tables-restore command still not found.

**Comment by mrhotio** [comment]
```
74a07ef78850:/# which ip6tables-restore
/sbin/ip6tables-restore
74a07ef78850:/#
```

must be an issue on your end then
